sudo: required
services:
  - docker

before_install:
  - docker build -t testimg -f Dockerfile.dev .

script:
  - docker run testimg npm run test -- --coverage

#deploy:
#  provider: elasticbeanstack
#  resion:   "us-west-2"
# app: "docker"
#  env: "Docker-env"
#  bucket_naem: ""
#  bucket_path: ""
#  on: 
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "AWS_SECRET_KEY"


  
